### ISSUE TITLE
User: lastname/middle name

### ISSUE THREAD

**Issue by FelixAkk** [buitensportdurf/runtracker-api#8]
Looks like e.g. `Kater de` is transformed into `Katerde`. Looks like the SBN adds the middle name after the lastname (`van de Leeuw` becomes `Leeuw van de` for their alphabetic sorting purposes). Possible to extract the middle name during parsing and put into `middleName` property? 😄 

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1232909/100522920-ace8b580-31ac-11eb-8caa-77c097a6d00f.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/1232909/100522942-d1449200-31ac-11eb-8fd8-d8c7709ea65c.png">

**Comment by ardentsword** [comment]
First version fixed in 4650f97e0ff3ed9a314b156fe0255b2e8ffe4dfe
